### PR TITLE
iOS Support

### PR DESCRIPTION
**Pull request by luxxxxy**
Renames the "macos" module to "darwin", exposes it to both macOS and iOS.

The "darwin" module is also exposed as "macos" on macOS targets, for backwards compatibility.

### CODE REVIEW

**Comment by luxxxxy** [comment]
Compiles successfully on my iPhone 11 (iOS 13.5, rust 1.46.0 nightly, A13 Bionic CPU)

**Comment by dcuddeback** [comment]
@luxxxxy Please read the contributing guidelines to be sure you're following the requirements for submitting a patch. I have family matters to deal with right now, so it will be at least a few weeks before I can take a look. That should give you plenty of time to get the patch ready.

**Comment by luxxxxy** [comment]
`cargo test` passes.

WindowsTerminal_trfjFEPMng


iOS and macOS are one of the few cases where you can fully expect code like this to just be copy-pasted and fully work. Why? They both use the same kernel, Darwin. That's like saying you couldn't use the same code on Raspbian and Arch Linux.

**Comment by dcuddeback** [comment]
> That's like saying you couldn't use the same code on Raspbian and Arch Linux - same kernel, different CPU architectures.

@luxxxxy Linux *does* have different definitions for different architectures. I spent a lot of time writing the contributing guidelines to avoid low-effort PRs like this. It's not your place to second-guess those guidelines. Please follow the instructions for submitting patches if you'd like to be taken seriously.

**Comment by luxxxxy** [comment]
Ok, sure. Call my attempts to attempt to get the Rust ecosystem into a working state "low-effort".

P.S: the termios.h in the macOS SDK and in the iOS sdk are bit-by-bit identical.
```
aleister on VMacOS in ~
❯ sha256sum /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/sys/termios.h
5c67e66b1d0ff5171ac452eb0ddfa6688690eeae8466306a8649730fb21aa4fa  /Library/Developer/CommandLineTools/SDKs/MacOSX10.14.sdk/usr/include/sys/termios.h

aleister on VMacOS in ~
❯ sha256sum /Library/Developer/CommandLineTools/SDKs/iPhoneOS.sdk/usr/include/sys/termios.h
5c67e66b1d0ff5171ac452eb0ddfa6688690eeae8466306a8649730fb21aa4fa  /Library/Developer/CommandLineTools/SDKs/iPhoneOS.sdk/usr/include/sys/termios.h
```

**Comment by dcuddeback** [comment]
@luxxxxy has been blocked for their conduct in this thread. If anyone sees this and would like to contribute iOS support, please see the contributing guidelines. They're there for a reason.

**Comment by MCApollo** [comment]
@dcuddeback See https://docs.rs/nix/0.13.0/src/nix/sys/termios.rs.html#301, iOS is treated the same as MacOS in a sister package. @luxxxxy has been making efforts to support cargo and the rustc compiler on iOS (which only had libstd support).

iOS should be the same as any OSX device out-there, especially with such a old API. You can follow the headers at a Xcode installation or [here](https://github.com/theos/sdks/blob/master/iPhoneOS11.2.sdk/usr/include/termios.h). 

Feel free to ask any more questions if you need, thanks!

**Comment by dcuddeback** [comment]
@MCApollo The questions that need answering are in the contributing guidelines. I'll be happy to look at patches that put in a good faith effort to follow those guidelines, but I will not engage in arguments that to rationalize why the rules don't apply to this PR.

**Pull request closed without merging**
