### PR TITLE
Add support for DragonFlyBSD

### PR DESCRIPTION
**Pull request by mneumann**
Reuse the freebsd module, but export it as "dragonfly".

### CODE REVIEW

**Comment by mneumann** [comment]
@dcuddeback Any chance to get this merged in, and a 0.2.3 release?

**Comment by dcuddeback** [comment]
@mneumann Yeah. I need to setup a VM with Dragonfly BSD to test with. I just got back from vacation, but will try to do that soon.

**Comment by mneumann** [comment]
@dcuddeback Cool! If you need help with setting up DragonFly, let me know. We have rust and cargo in ports, so you can install them via "pkg install rust cargo".

**Comment by dcuddeback** [comment]
@mneumann After a few false-starts, I was able to get rustc and cargo installed on DragonFly BSD 5.0. Not sure why it wasn't working for me before. I was hoping to wrap this up before flying home for Thanksgiving, but it looks like that's not going to happen. I compared `freebsd.rs` to the definitions in `<termios.h>` and found a few differences. I pushed up a branch [`feature/dragonfly`](https://github.com/dcuddeback/termios-rs/compare/feature/dragonfly) with a new module for dragonfly. That should work. The main thing holding me back from releasing it right now is that it breaks the API in `src/lib.rs`, since DragonFly BSD doesn't export `TAB3`. I **think** just removing `TAB3` from the reexports in `src/lib.rs` should be fine, which is [what I did](https://github.com/dcuddeback/termios-rs/compare/feature/dragonfly#diff-b4aea3e418ccdb71239b96952d9cddb6L119) in `feature/dragonfly`, but I need to think about it some more before I release that. I'll bump the version to v0.2 if I do that since that's technically a breaking change.

**Comment by dcuddeback** [comment]
@mneumann Termios definitions for DragonFly are now in master, and I just released v0.3.0 to crates.io with the new definitions. Dropping `TAB3` from the crate root is consistent with the goal of keeping the crate root portable, and turns out to be we did when adding FreeBSD support too (https://github.com/dcuddeback/termios-rs/pull/3), so I went with that. Thanks for being patient.

**Comment by mneumann** [comment]
@dcuddeback : Thanks!

**Pull request closed without merging**
