### PR TITLE
Add the OpenBSD termios definitions.

### PR DESCRIPTION
**Pull request by qbit**

### CODE REVIEW

**Comment by conradkleinespel** [comment]
+1 @qbit, awesome of you to take the time to do this !

**Comment by dcuddeback** [comment]
@qbit :+1: Nice! I love to see new platforms being supported. I've been wanting to try OpenBSD in particular for a while.

**Comment by qbit** [comment]
@dcuddeback Some awesome stuff happening in OpenBSD (pledge, native hypervisor.. etc)! Give it a shot for sure!

**Comment by qbit** [comment]
Any chance the cargo version can be bumped so projects with termios as a dep can update?

**Comment by dcuddeback** [comment]
@qbit Yes, definitely. I just got Rust and Cargo working on OpenBSD 5.9 this morning. I should be able to publish a new version to crates.io tonight after work.

**Comment by qbit** [comment]
:+1: Thanks!

**Comment by dcuddeback** [comment]
@qbit It's pushed.

**Comment by qbit** [comment]
Thanks!

**Pull request merged**
